#!/bin/sh

GRAPH=IS-script-calls

command_exists () { type "$1" &> /dev/null ; }

if ! command_exists dot ; then module load graphviz ; fi

dot -Tpng -o${GRAPH}.png ${GRAPH}.gv

if [[ $? -eq 0 ]] ; then
    gnome-open ${GRAPH}.png
fi
