/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Unix */

#ifndef _Included_Unix
#define _Included_Unix
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Unix
 * Method:    doRestartQ315
 * Signature: ()I
 */

JNIEXPORT void JNICALL Java_gda_util_Unix_doRestartQ315(JNIEnv *, jclass);


/*
 * Class:     Unix
 * Method:    doGetDiskMB
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doGetDiskMB
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Unix
 * Method:    doGetFreeMB
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jlong JNICALL Java_gda_util_Unix_doGetFreeMB
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Unix
 * Method:    doStartBLDaemon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doStartBLDaemon
  (JNIEnv *, jobject);

/*
 * Class:     Unix
 * Method:    doStartQ4Xform
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doStartQ4Xform
(JNIEnv *env, jobject obj);
  
/*
 * Class:     Unix
 * Method:    doStart345Daemon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doStart345Daemon
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Unix
 * Method:    doEndt345Daemon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doEnd345Daemon
  (JNIEnv *, jobject);

/*
 * Class:     Unix
 * Method:    doStartMarSimulator
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doStartMarSimulator
  (JNIEnv *, jobject);

/*
 * Class:     Unix
 * Method:    doEndMarSimulator
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doEndMarSimulator
  (JNIEnv *, jobject);

/*
 * Class:     Unix
 * Method:    doStartMarDaemon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doStartMarDaemon
  (JNIEnv *, jobject);

/*
 * Class:     Unix
 * Method:    doEndMarDaemon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doEndMarDaemon
  (JNIEnv *, jobject);
/*
 * Class:     Unix
 * Method:    doStart345Simulator
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doStart345Simulator
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Unix
 * Method:    doSystem
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doSystem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Unix
 * Method:    doResetXformStatusFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gda_util_Unix_doResetXformStatusFile
(JNIEnv *env, jobject obj);
  
/*
 * Class:     Unix
 * Method:    initFIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gda_util_Unix_initFIDs
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_gda_util_Unix_doGetSocketState(JNIEnv *env, jobject this, jint fd, jobject ret);

#ifdef __cplusplus
}
#endif
#endif
