/*-
 * Copyright © 2021 Diamond Light Source Ltd.
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

package uk.ac.diamond.daq.beamline.k11.diffraction.view.summary.editor;

import java.text.DecimalFormat;
import java.util.List;

/**
 * Represents a set of {@link Segment}s belonging to a common structure, i.e. an array.
 *
 * @param <T> the numeric structure represented by this group
 *
 * @author Maurizio Nagni
 */
public interface SegmentGroup<T> {
	/**
	 * The group numeric string format
	 *
	 * @return a formatted instance
	 */
	public DecimalFormat getDecimalFormat();
	/**
	 * The {@code Segment} belonging to this group
	 *
	 * @return a list of segments
	 */
	public List<Segment<T>> getSegments();
	/**
	 * Traversing all the group segments, recreate the structure represented by this group
	 *
	 * @return the original structure
	 */
	public T getValues();
	/**
	 * Persist the numerical structure. After calling this method the the numerical structure should be equivalent to the one
	 * generated by {@link #getValues()}
	 */
	public void persist();
	/**
	 * Defines when the group is editable
	 *
	 * @return {@code true} when editable, otherwise {@code false}
	 */
	public boolean isEditable();
}