finder.find("kphi_motor").home()
finder.find("kappa_motor").home()
finder.find("kth_motor").home()
finder.find("delta_motor").home()
delta(90)
finder.find("mu_motor").home()
finder.find("gam_motor").home()