#! /bin/sh

INSTALLDIR=/dls_sw/i12/software/gda/config/scripts/EDXD/python/edxd_tools
PYTHONPATH=$INSTALLDIR:/dls_sw/apps/numpy/1.3.0/lib/python2.6/site-packages
export PYTHONPATH
LD_LIBRARY_PATH=/dls_sw/apps/nexus/4.2.0/lib/:/dls_sw/apps/nexus/4.2.0/hdf4/lib/:/dls_sw/apps/nexus/4.2.0/hdf5/lib/:/dls_sw/apps/nexus/4.2.0/mxml/lib/ 
export LD_LIBRARY_PATH

/dls_sw/apps/python/2.6.2/bin/python $INSTALLDIR/edxd/remap_q_axis.py $@
