VAR_DIFFRACTION = "dls_sw/b16/software/var_diffraction/"

DEF_ECR = "ecr.xml"
DEF_ECR_PATH = VAR_DIFFRACTION + DEF_ECR

DEF_SAMPLE = "sample.xml"
DEF_SAMPLE_PATH = VAR_DIFFRACTION + DEF_SAMPLE

DEF_VISIT = ""
DEF_VISIT_FOLDER = "/dls/b16/data/2021/" + DEF_VISIT + "/"


ACTION_ALL = "ALL"
ACTION_PREPARE = "PREPARE"
ACTION_EXPOSE = "EXPOSE"

