'''
Created on 9 Jun 2015

@author: fy65
'''

FORCE_PV="BL11I-EA-SPUMP-01:FORCE"
FORCE_RBV_PV="BL11I-EA-SPUMP-01:FORCE:RBV"
TARGET_TIME_PV="BL11I-EA-SPUMP-01:TTIME"
TARGET_TIME_RBV_PV="BL11I-EA-SPUMP-01:TTIME:RBV"
DIAMETER_PV="BL11I-EA-SPUMP-01:DIAMETER"
DIAMETER_RBV_PV="BL11I-EA-SPUMP-01:DIAMETER:RBV"
INFUSE_RATE_PV="BL11I-EA-SPUMP-01:IRATE"
INFUSE_RATE_RBV_PV="BL11I-EA-SPUMP-01:IRATE:RBV"
INFUSE_RATE_UNIT_PV="BL11I-EA-SPUMP-01:IRATEUNITS"
INFUSE_RATE_UNIT_RBV_PV="BL11I-EA-SPUMP-01:IRATEUNITS:RBV"
WITHDRAW_RATE_PV="BL11I-EA-SPUMP-01:WRATE"
WITHDRAW_RATE_RBV_PV="BL11I-EA-SPUMP-01:WRATE:RBV"
WITHDRAW_RATE_UNIT_PV="BL11I-EA-SPUMP-01:WRATEUNITS"
WITHDRAW_RATE_UNIT_RBV_PV="BL11I-EA-SPUMP-01:WRATEUNITS:RBV"
INFUSED_VOL_RBV_PV="BL11I-EA-SPUMP-01:IVOLUME:RBV"
INFUSED_VOL_UNIT_RBV_PV="BL11I-EA-SPUMP-01:IVOLUMEUNITS:RBV"
CLEAR_INFUSED_VOL_PV="BL11I-EA-SPUMP-01:CLEARINFUSED"
WITHDRAWN_VOL_RBV_PV="BL11I-EA-SPUMP-01:WVOLUME:RBV"
WITHDRAWN_VOL_UNIT_RBV_PV="BL11I-EA-SPUMP-01:WVOLUMEUNITS:RBV"
CLEAR_WITHDRAWN_VOL_PV="BL11I-EA-SPUMP-01:CLEARWITHDRAWN"
TARGET_VOL_PV="BL11I-EA-SPUMP-01:TVOLUME"
TARGET_VOL_RBV_PV="BL11I-EA-SPUMP-01:TVOLUME:RBV"
TARGET_VOL_UNIT_PV="BL11I-EA-SPUMP-01:TVOLUMEUNITS"
TARGET_VOL_UNIT_RBV_PV="BL11I-EA-SPUMP-01:TVOLUMEUNITS:RBV"


class HASyringePump(object):
    '''
    classdocs
    '''


    def __init__(self, params):
        '''
        Constructor
        '''
        