'''
a metadata scannable used to obtain the harmonic of the X-ray beam generated by Insertion Device in I06.
Created on Sep 1, 2021

@author: fy65
'''
from gda.device.scannable import ScannableMotionBase
from i06shared.scannables.sourceModes import SourceMode

class HarmonicScannable(ScannableMotionBase):
    '''
    classdocs
    '''


    def __init__(self, name, smode, iddhar, iduhar):
        '''
        Constructor
        '''
        self.setName(name)
        self.setInputNames([name])
        self.setOutputFormat(["%d"])
        self.smode = smode
        self.iddhar = iddhar
        self.iduhar = iduhar
    
    def getPosition(self):
        mode = str(self.smode.getPosition())
        if mode == SourceMode.SOURCE_MODES[0]:
            return int(self.iddhar.getPosition())
        elif mode == SourceMode.SOURCE_MODES[1]:
            return int(self.iduhar.getPosition())
        else:
            return "Cannot determine ID harmonic in source mode %s" % mode
    
    def asynchronousMoveTo(self):
        print("%s is a Read-Only scannable used for metadata." % self.getName())
    
    def isBusy(self):
        return False
