'''
a metadata scannable used to obtain the harmonic of the X-ray beam generated by Insertion Device in I06.
Created on Sep 1, 2021

@author: fy65
'''
from gda.device.scannable import ScannableMotionBase

class HarmonicScannable(ScannableMotionBase):
    '''
    classdocs
    '''


    def __init__(self, name, pol):
        '''
        Constructor
        '''
        self.setName(name)
        self.setInputNames([name])
        self.setOutputFormat(["%d"])
        self.pol = pol
    
    def getPosition(self):
        if str(self.pol.getPosition()) == "lh3":
            return 3
        else:
            return 1
    
    def asynchronousMoveTo(self):
        print("%s is a Read-Only scannable used for metadata." % self.getName())
    
    def isBusy(self):
        return False
