// This code has been generated by the code Wizard and should not be
// modified.  The recommended manner of changing the behavior is to
// implement a class that inherits from this generated class.

package helloworldex;

import com.idl.javaidl.*;

public class helloworldex extends JIDLObject
{
   // Constants set by Wizard
   private static String IDL_CLASS = "helloworldex";
   private static String OPS_NAME  = "Default_Process_Name";

   // Constructor
   public helloworldex() {
      super(IDL_CLASS, OPS_NAME);
   }

   // properties generated by Wizard

   // class methods generated by Wizard

   public JIDLString HELLOFROM(
      JIDLString WHO
      )
   {
      final int ARGC = 1;
      Object[] argv = new Object[ARGC];
      int[] argp = new int[ARGC];

      Object result = null;
      final int FLAGS = 0;

      // Parameter assignments
      argv[0] = WHO;
      argp[0] = JIDLConst.PARMFLAG_CONST;

      result = super.callFunction("HELLOFROM",
         ARGC, argv, argp, FLAGS);


      return (JIDLString)result;
   }

}
