#!/bin/sh

if [ -z ${SCAN-} ] ; then
  echo "No SCAN environment variable defined! Exiting..."
  exit 1
fi

[ -e       processed/${SCAN}_msmapper.nxs ] && \
nxls    -a processed/${SCAN}_msmapper.nxs > ${SCAN}_msmapper.nxs.nxlsa && \
nexus.tree processed/${SCAN}_msmapper.nxs > ${SCAN}_msmapper.nxs.tree &
[ -e       processing/$SCAN-processed-volume-hkl.nxs ] && \
nxls    -a processing/$SCAN-processed-volume-hkl.nxs > $SCAN-processed-volume-hkl.nxs.nxlsa ; \
nexus.tree processing/$SCAN-processed-volume-hkl.nxs > $SCAN-processed-volume-hkl.nxs.tree &

wait

ls -altr $SCAN.* $SCAN*.nxlsa $SCAN*.tree
ls -altr processing/$SCAN*
