#!/bin/sh

if [ -z ${SCAN-} ] ; then
  echo "No SCAN environment variable defined! Exiting..."
  exit 1
fi
if [ -z ${BASELINE-} ] ; then
  echo "No BASELINE environment variable defined! Exiting..."
  exit 1
fi

[ -e     $BASELINE.nxs.ndw.nxlsa ] && [ -e $SCAN.nxs.ndw.nxlsa ] && \
  kdiff3 $BASELINE.nxs.ndw.nxlsa           $SCAN.nxs.ndw.nxlsa   &
[ -e     $BASELINE.nxs.ndw.nxlsa ] && [ -e $SCAN.nxs.nsd.nxlsa ] && \
  kdiff3 $BASELINE.nxs.ndw.nxlsa           $SCAN.nxs.nsd.nxlsa   &
[ -e     $BASELINE.nxs.nsd.nxlsa ] && [ -e $SCAN.nxs.nsd.nxlsa ] && \
  kdiff3 $BASELINE.nxs.nsd.nxlsa           $SCAN.nxs.nsd.nxlsa   &
[ -e     $BASELINE.nxs.ndw.tree  ] && [ -e $SCAN.nxs.ndw.tree ] && \
  kdiff3 $BASELINE.nxs.ndw.tree            $SCAN.nxs.ndw.tree   &
[ -e     $BASELINE.nxs.ndw.tree  ] && [ -e $SCAN.nxs.nsd.tree ] && \
  kdiff3 $BASELINE.nxs.ndw.tree            $SCAN.nxs.nsd.tree   &
[ -e     $BASELINE.nxs.nsd.tree  ] && [ -e $SCAN.nxs.nsd.tree ] && \
  kdiff3 $BASELINE.nxs.nsd.tree            $SCAN.nxs.nsd.tree   &
