'''
a metadata scannable used to obtain the harmonic of the X-ray beam generated by Insertion Device in I21.

Created on Sep 2, 2021

@author: fy65
'''
from gda.device.scannable import ScannableMotionBase

class HarmonicScannable(ScannableMotionBase):
    '''
    a scannable which gives the harmonic order of the X-ray beam
    '''


    def __init__(self, name, pol):
        '''
        Constructor
        '''
        self.setName(name)
        self.setInputNames([name])
        self.setOutputFormat(["%d"])
        self.pol = pol
    
    def getPosition(self):
        polar = str(self.pol.getPosition())
        if  polar == "LH3" or polar == "LV3":
            return 3
        elif  polar == "LH5" or polar == "LV5":
            return 5
        else:
            return 1
    
    def asynchronousMoveTo(self):
        print("%s is a Read-Only scannable used for metadata." % self.getName())
    
    def isBusy(self):
        return False
